"""Rename owner_id to user_id column

Revision ID: 000ca973603e
Revises: 17c0208c25ce
Create Date: 2026-02-04 12:02:02.198680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '000ca973603e'
down_revision = '17c0208c25ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, make the owner_id column nullable to avoid constraint violations
    op.alter_column('task', 'owner_id', nullable=True)
    # Now we can drop the owner_id column since we're using user_id
    op.drop_column('task', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###