"""Add user_id column to task table

Revision ID: 17c0208c25ce
Revises: 
Create Date: 2026-02-04 11:34:00.632750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '17c0208c25ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_id column to the task table
    op.add_column('task', sa.Column('user_id', sa.String(), nullable=False, server_default='unknown'))
    # Update the default values for existing records to a reasonable default
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###